name = "Origin"
uuid = "421443cc-9b00-11ea-1646-3bac74f84b0c"
authors = ["Hiroyuki Okamura"]
version = "0.1.2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
